name: Generate and Sync LaTeX PDF

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Identify the new folder with LaTeX file
    - name: Find New Folder and LaTeX File
      id: find_folder
      run: |
        # Find the newly added folder
        NEW_FOLDER=$(git diff --name-only origin/develop...HEAD | grep -E '^src/2 - RTB/.+/' | cut -d/ -f1-4 | sort | uniq)
        if [ -z "$NEW_FOLDER" ]; then
          echo "No new folder found. Exiting."
          exit 1
        fi
        echo "new_folder=$NEW_FOLDER" >> $GITHUB_ENV

        # Find the LaTeX file in the new folder
        LATEX_FILE=$(find "$NEW_FOLDER" -type f -name "*.tex" | head -n 1)
        if [ -z "$LATEX_FILE" ]; then
          echo "No LaTeX file found in $NEW_FOLDER. Exiting."
          exit 1
        fi
        echo "latex_file=$LATEX_FILE" >> $GITHUB_ENV

    # Step 3: Compile the LaTeX file
    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: ${{ env.latex_file }}
        latexmk_use_lualatex: true  # Cambia se preferisci pdflatex

    # Step 4: Move the PDF to the PDF folder in Develop
    - name: Add PDF to Develop
      if: github.event_name == 'pull_request'
      run: |
        PDF_FILE="${{ env.latex_file%.tex }}.pdf"
        mv "$PDF_FILE" PDF/
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add PDF/
        git commit -m "Add compiled PDF for PR #${{ github.event.pull_request.number }}"
        git push origin develop

    # Step 5: Sync the PDF to Main
    - name: Sync PDF to Main
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout main
        cp -r PDF/ PDF/
        git add PDF/
        git commit -m "Sync PDF to Main"
        git push origin main
