name: Compile LaTeX and Update Main

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

defaults:
  run:
    shell: bash
    working-directory: ${{ github.workspace }}

jobs:
  build-and-move-pdf:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Identify LaTeX files
        id: find_latex
        run: |
          latex_files=$(find . -type f -name '*.tex')
          echo "::set-output name=files::$latex_files"

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX files to PDF
        id: compile
        run: |
          for file in ${{ steps.find_latex.outputs.files }}; do
            dir=$(dirname "$file")
            base=$(basename "$file" .tex)

            cd "$dir"
            pdflatex "$base.tex" || exit 1
            cd -
          done

      - name: Push PDFs to Main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git checkout main
          for file in ${{ steps.find_latex.outputs.files }}; do
            dir=$(dirname "$file" | cut -d'/' -f2-)
            base=$(basename "$file" .tex)

            pdf_file="$dir/$base.pdf"

            # Ensure the directory structure exists in the main branch
            mkdir -p "$dir"

            mv "$file" "$dir/"
            git add "$dir/$base.pdf"
          done

          git commit -m "Add compiled PDFs from PR #${{ github.event.pull_request.number }}"
          git push
